### ISSUE TITLE
Bugs will be fixed

### ISSUE THREAD

**Issue by MagicLu550** [jsmod2-java-c/JSmod2-Core#4]
以下以中文版:
1.Linux下，控制台的行分离的诡异问题
2.Windows下，不支持的彩色字符和乱码问题
3.其他问题如果被发现，请上传(尽量使用中英双语版)

The following is in English:
1.Under the Linux, the problem of the separation of the console line
2.Unsupported color characters and garbled problems under Windows
3. If other issues are found, please upload (try to use Chinese and English bilingual versions)

**Comment by YorokobiMaster** [comment]
Finished :)
