### ISSUE TITLE
ui does not match the actual

### ISSUE THREAD

**Issue by fafa-junhe** [jsmod2-java-c/JSMod2-Core#5]
**Describe the bug**
ui does not match the actual

**To Reproduce**
1. Open the jsmod2

**Expected behavior**
to  be expected:
![_DPQRGW5YC XI@_S$GA 5(E](https://user-images.githubusercontent.com/22996240/61788912-e8030800-ae45-11e9-9e92-990a0f06d479.png)

actual:
![7(Z~N 6BTR%28FAXI(H (KU](https://user-images.githubusercontent.com/22996240/61788921-e9cccb80-ae45-11e9-807c-6d508ffe47e6.png)

and the border can be dragged
**Desktop (please complete the following information):**
 - OS: Linux
 - Version : qqgrouptestversion

**描述错误**
ui与实际不符

**重现**
重现行为的步骤：
1.打开jsmod2

**预期行为**
预期：
![_DPQRGW5YC XI@_S$GA 5(E](https://user-images.githubusercontent.com/22996240/61788912-e8030800-ae45-11e9-9e92-990a0f06d479.png)

实际：
![7(Z~N 6BTR%28FAXI(H (KU](https://user-images.githubusercontent.com/22996240/61788921-e9cccb80-ae45-11e9-807c-6d508ffe47e6.png)

并且可以拖动边框
**桌面（请填写以下信息）：**
   - 操作系统：Linux
   - 版本: qqgrouptestversion

**Comment by fafa-junhe** [comment]
Windows can also reproduce this bug

**Comment by MagicLu550** [comment]
Ok, we have received the information and will be resolved in a future release. Thank you for your proposal.

**Comment by fafa-junhe** [comment]
I think I should use exit instead of stop

https://ux.stackexchange.com/questions/50893/do-we-exit-quit-or-close-an-application

**Comment by MagicLu550** [comment]
ok,i will

**Comment by MagicLu550** [comment]
The bug has been resolved
